# Generated by Django 4.0.4 on 2022-07-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='material',
            field=models.CharField(choices=[('S', 'Steel'), ('P', 'Plastic'), ('T', 'Tempered Glass')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='case',
            name='type',
            field=models.CharField(choices=[('T', 'Tower'), ('M', 'Mid Tower'), ('B', 'Box')], default='T', max_length=1),
        ),
        migrations.AlterField(
            model_name='component',
            name='hardware',
            field=models.CharField(choices=[('M', 'Memory Card'), ('C', 'CPU'), ('B', 'Mother Board'), ('P', 'Power Supplies'), ('S', 'Storage'), ('A', 'CPU Cooler'), ('V', 'Video Card'), ('O', 'Operating System')], default='M', max_length=1),
        ),
    ]
