# Generated by Django 4.0.4 on 2022-07-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='picture',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
