# Generated by Django 4.0.4 on 2022-07-20 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_component_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='picture',
        ),
    ]
