# Generated by Django 4.0.4 on 2022-07-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_case_material_alter_case_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='material',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='component',
            name='hardware',
            field=models.CharField(max_length=255),
        ),
    ]
