# Generated by Django 4.0.4 on 2022-07-20 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_component_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='name',
            new_name='brand',
        ),
    ]
