# Generated by Django 4.0.4 on 2022-07-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_component_alter_comment_comment_alter_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='components',
            field=models.ManyToManyField(to='main_app.component'),
        ),
    ]
