# Generated by Django 4.0.4 on 2022-07-19 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_comment_comment_alter_comment_name'),
        ('main_app', '0005_case_components'),
    ]

    operations = [
    ]
