# Generated by Django 4.0.4 on 2022-07-19 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_merge_20220719_0229'),
        ('main_app', '0006_merge_20220719_0230'),
    ]

    operations = [
    ]
